### ISSUE TITLE
in portable version. "Failed to execute script music_caster due to unhandled exception: [WinError 6] the handle is invalid"

### ISSUE THREAD

**Issue by onegrasshopper** [elibroftw/music-caster#31]
win10, latest version.

fyi, the install version works, but the portable version throws an error. In new folder so no old settings. 
No log file generated.  

"Unhandled exception in script" window contents:

Traceback (most recent call last):
  File "music_caster.py", line 163, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 493, in exec_module
  File "helpers.py", line 31, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 493, in exec_module
  File "deemix\__main__.py", line 9, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 493, in exec_module
  File "deemix\settings.py", line 24, in <module>
  File "deemix\utils\localpaths.py", line 56, in getMusicFolder
  File "os.py", line 983, in popen
  File "subprocess.py", line 808, in __init__
  File "subprocess.py", line 1146, in _get_handles
OSError: [WinError 6] The handle is invalid

**Comment by elibroftw** [comment]
I've fixed the issue but can you delete/edit out the trace back? I just don't want the trace back to be public. Also I suggest installing the app (setup.exe) because the portable version has to extract itself before running the program.
